data_path: "../datasets/CORD-NERD/test/"
batch_size: 1
entry_type: "onto.medical.MedicalEntityMention"

reader:
  class_name: "showcase.readers.CORDReader"
  config:

processors: 
  word_tokenizer:
    class_name: "forte.processors.third_party.NLTKWordTokenizer"
    config:

  sentence_segmenter:
    class_name: "showcase.processors.NLTKSentSegEntityCautious"
    config:
      entity_mention_type: "onto.medical.MedicalEntityMention"
    
  remove_duplicate_entries:
    class_name: "showcase.processors.DeleteOverlapEntry"
    config:
      entry_type: "onto.medical.MedicalEntityMention"
  
  subword_tokenizer:
    class_name: "forte.processors.nlp.SubwordTokenizer"
    config:
      pretrained_model_name: "biobert-v1.1-pubmed"

ner_predict:
  predict_path: "./sample_output/ner_bio/"
  attribute: 'ner_type'
  config: 
    scope: "ft.onto.base_ontology.Sentence"
    batch_size: 1
    do_eval: True
    feature_scheme:
      input_tag:
        type: "data_input"
        extractor:
          class_name: "forte.data.extractors.SubwordExtractor"
          config:
            entry_type: "ft.onto.base_ontology.Subword"
            vocab_method: "indexing"
            need_pad: False
            vocab_use_unk: False
            pretrained_model_name: "biobert-v1.1-pubmed"
      output_tag:
        type: "data_output"
        extractor:
          class_name: "forte.data.extractors.BioSeqTaggingExtractor"
          config:
            entry_type: "onto.medical.MedicalEntityMention"
            attribute: "ner_type"
            tagging_unit: "ft.onto.base_ontology.Subword"
            vocab_method: "indexing"
            vocab_use_unk: False
            is_bert: True
            pad_value: -100
          vocab_path:

linking_predict:
  predict_path: "./sample_output/linking_medical/"
  attribute: 'umls_link'
  config: 
    scope: "ft.onto.base_ontology.Sentence"
    batch_size: 1
    do_eval: False
    feature_scheme:
      input_tag:
        type: "data_input"
        extractor:
          class_name: "forte.data.extractors.SubwordExtractor"
          config:
            entry_type: "ft.onto.base_ontology.Subword"
            vocab_method: "indexing"
            need_pad: False
            vocab_use_unk: False
            pretrained_model_name: "biobert-v1.1-pubmed"
      output_tag:
        type: "data_output"
        extractor:
          class_name: "forte.data.extractors.BioSeqTaggingExtractor"
          config:
            entry_type: "onto.medical.MedicalEntityMention"
            attribute: "umls_link"
            tagging_unit: "ft.onto.base_ontology.Subword"
            vocab_method: "indexing"
            vocab_use_unk: False
            is_bert: True
            pad_value: -100
          vocab_path:
